
services:
  server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: final  # Specifica il target di build
    image: mattiadispigno/sagradafamilia-server:v1
    environment:
      - ConnectionStrings__MyDbContext=${DB_CONN_STRING}
#      - Jwt__Key=${MY_SECRET}
    ports:
      - 8080:8080
    depends_on:
      - sqlserver
    networks:
       - app_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${SQL_CONT_NAME:-sqlserver_container}
    restart: always
    environment:
      SA_PASSWORD: ${DB_CONN_PASS}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
       - app_network

networks:
      app_network:
    
volumes:
      sqlvolume: