services:
  server:
    image: mattiadispigno/sagradafamilia-server:latest
    platform: ${MY_PLATFORM:-linux/amd64}
    environment:
      AllowedIpsConfig__AllowedIps: '["http://localhost:8080","http://localhost:8000","http://localhost:5173"]'
      ConnectionStrings__MyDbContext: ${DB_CONN_STRING}
      Jwt__Key: ${MY_SECRET}
      Jwt__Issuer: http://localhost:8080
      Jwt__Audience: http://localhost:8080
    ports:
      - 8080:8080
    depends_on:
      - sqlserver
    networks:
       - app_network

  sqlserver:
    #image: mcr.microsoft.com/azure-sql-edge:latest
    #se usate l'immagine di sqlserver, commentate la riga sopra   
    #e decommentate la riga sotto
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: ${SQL_CONT_NAME:-sqlserver}
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - database_volume:/var/opt/mssql
    restart: always
    networks:
       - app_network

    healthcheck:
      #usando sqlserver, decommentate:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -C
      #e commentate la riga sotto
      #test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD}
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
      
  sqlserver.configurator:
    #image: mcr.microsoft.com/azure-sql-edge:latest
    #se usate l'immagine di sqlserver, commentate la riga sopra   
    #e decommentate la riga sotto
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver.configurator
    
    #Creare una cartella init nella root del progetto e mettere dentro init.sql
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    #usando sqlserver, decommentate:
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S ${SQL_CONT_NAME:-sqlserver} -U sa -P ${SA_PASSWORD} -d master -i docker-entrypoint-initdb.d/init.sql -C;
      echo "All done!";
      '
    #e commentate la riga sotto
    #command: >
    #  bash -c '
    #  /opt/mssql-tools/bin/sqlcmd -S ${SQL_CONT_NAME:-sqlserver} -U sa -P ${SA_PASSWORD} -d master -i docker-entrypoint-initdb.d/init.sql;
    #  echo "All done!";
    #  '
    networks:
      - app_network
volumes:
  database_volume:

networks:
  app_network:
