services:
  server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: final  # Specifica il target di build
    image: mattiadispigno/sagradafamilia-server:latest
    platform: ${MY_PLATFORM:-linux/amd64}
    environment:
      AllowedIpsConfig__AllowedIps: '["http://localhost:8080","http://localhost:8000","http://localhost:5173"]'
      ConnectionStrings__MyDbContext: ${DB_CONN_STRING}
      Jwt__Key: ${MY_SECRET}
      Jwt__Issuer: http://localhost:8080
      Jwt__Audience: http://localhost:8080
    ports:
      - 8080:8080
    depends_on:
      - azure-sql-edge
    networks:
       - app_network

  azure-sql-edge:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: ${MY_PLATFORM:-linux/amd64}
    container_name: ${SQL_CONT_NAME:-sqlserver_container}
    restart: always
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-edge-data:/var/opt/mssql
    networks:
       - app_network

networks:
      app_network:
    
volumes:
      sql-edge-data: